Library/Spells/Magic.spl
There are several spells in Magic.spl that don't actually match the names used
in GURPS Magic. This changes them to match. I don't know if you necessarily want this -- for some of these I could believe this is a ~difference in your style guide, and even for the others I don't know if this breaks things for existing characters (looks like no?). Anyway, I was trying to merge information from the GCS spell list and another one and ran across these discrepancies, so figured I'd submit this. (Also, sorry if PR's are the wrong way to suggest changes. Since I had a patch, I figured this might be the easiest.)
Summary of changes:
- Change plural/non-plural status of spells
- "Rain Ice Daggers" is "Rain of Ice Daggers"
- "Remove Enchant" is "Remove Enchantment"
- "Steel Wraith" is "Steelwraith"
- …
=> Spelling and standardization fixes to match GURPS Magic

Library/Spells/Magic.spl, Library/Spells/Wizardry Redefined.spl
Wizardry Refined is some tweaks to the spells for Dungeon Fantasy.  I put it in a new file rather than modifying the existing Magic.spl and Dungeon Fantasy.spl, so players have options.
Also found a few little errors in Magic.spl while I was doing this.
=> Wizardry Refined from Pyramid 3/60, plus some small Magic prereq fixes

src/com/trollworks/gcs/skill/SkillAttribute.java, src/com/trollworks/gcs/skill/SkillDefaultType.java
Partially solves https://gurpscharactersheet.atlassian.net/browse/GCS-25
While this simple change doesn't allow to directly choose advantage for `10+<advantage name>` format, it can be solved by making advantage to add its level to all required skills (which Magery already does). So, better than nothing, I guess?
=> Allow skills and spells to be based on 10 rather then any attribute.

src/com/trollworks/gcs/character/GURPSCharacter.java, src/com/trollworks/gcs/character/PrerequisitesThread.java
https://gurpscharactersheet.atlassian.net/browse/GCS-152
I wasn't sure where notification for preference change should be handled, but other options that affect point cost use PrerequisitesThread, so I went with it.
=> Fixed SM incorrectly affecting ST cost when KYOS rules are enabled.

src/com/trollworks/gcs/character/GURPSCharacter.java
Because of my change for skill containers (to show sum of all underlying skills) they are sometimes being used as valid skill defaults.
Kalos reported this bug on discord.
https://i.gyazo.com/6fb5161c2f4b40d8114bd0c3a361a2b2.png
=> Fixed skill containers affecting skill defaults

src/com/trollworks/gcs/weapon/MeleeWeaponStats.java, src/com/trollworks/gcs/weapon/WeaponStats.java
GURPS B208: Fencing weapons getting a penalty equal to the encumbrance
level to attacks and parries
=> Encumbrance penalty for fencing weapon

src/com/trollworks/gcs/character/TextTemplate.java, src/com/trollworks/gcs/widgets/outline/MultiCell.java
#2 (in a series).
This fixes the spelling error on the literal, and updates the code that determines which piece of equipment provides the DR bonus during the text output to support armor that covers "Full Body" or "Full Body except the eyes".
=> Fixed spelling of literal, and minor enhancement TextOutput

src/com/trollworks/gcs/advantage/Advantage.java, src/com/trollworks/gcs/advantage/AdvantageColumn.java, src/com/trollworks/gcs/equipment/Equipment.java, src/com/trollworks/gcs/equipment/EquipmentColumn.java, src/com/trollworks/gcs/skill/Skill.java, src/com/trollworks/gcs/skill/SkillColumn.java, src/com/trollworks/gcs/spell/Spell.java, src/com/trollworks/gcs/spell/SpellColumn.java, src/com/trollworks/gcs/weapon/WeaponColumn.java, src/com/trollworks/gcs/weapon/WeaponDisplayRow.java
The next step to extending tooltips.   Subclasses of Row (Advantage, Equipment, Skill, Spell and WeaponDisplayRow) now override the Row behavior and ask their respective columns if they should be showing a tooltip for that column (default is false), and if so, what tooltip to show based on the Row element (default to the generic tooltip for that column).
=> Extended tooltip framework to Row/ListRow subclasses

src/com/trollworks/gcs/skill/Skill.java, src/com/trollworks/gcs/skill/SkillLevel.java
The main feature of this PR is that Skill will now use an instance of SkillLevel to store level and relative level, instead of using ints.    
You had a question about performance, so I did some math, and even with hundreds of skills, I don't think that will be a problem.   SkillLevel is a very light class (2 ints and a String).   Which uses 16 bytes for the object header, 8 bytes per int, 8 bytes for String pointer.   And then you have to add in the usage for the tooltip string itself, which averages out to "length of string * 6" bytes (a rough calculation of the number of bytes necessary to hold a string, obtained from research I did a few years ago).   
A Skill with no modifiers will have a tooltip of approx 25 characters/150 bytes (it reports "no additional modifiers").  On average, …
=> Converted Skill to use SkillLevel

src/com/trollworks/gcs/character/GURPSCharacter.java, src/com/trollworks/gcs/character/PrerequisitesThread.java, src/com/trollworks/gcs/feature/Bonus.java, src/com/trollworks/gcs/skill/Skill.java, src/com/trollworks/gcs/skill/SkillColumn.java, src/com/trollworks/gcs/skill/SkillLevel.java, src/com/trollworks/gcs/skill/Technique.java
This is the first of a few tooltip PRs.  I just did Skill (and Technique) in this PR so you can see how it is done.   Future PRs will cover Spells and WeaponDamage.
1.  Bonus received a "parent" variable.   This is the ListRow subclass that is providing the aforementioned bonus.  This variable is in essence, transient, since it is not read in from or streamed out to XML.
2.  PrerequisitesThread now stores the "parent" into the Bonus as it is being added to the character's feature map.
3.  SkillLevel was modified to accept a StringBuilder as its toolTip parameter, instead of a String (but it still only stores the String).   This allowed me to refactor the internationalized strings so they only exist in the SkillLevel class, instead of the ListRow subclasses.
4.  GURPSCharacter was modified …
=> Added tooltip for Skill level calculation

src/com/trollworks/gcs/app/GCS.java, src/com/trollworks/gcs/character/GURPSCharacter.java, src/com/trollworks/gcs/character/PrerequisitesThread.java, src/com/trollworks/gcs/spell/Spell.java, src/com/trollworks/gcs/spell/SpellColumn.java, src/com/trollworks/gcs/weapon/WeaponColumn.java, src/com/trollworks/gcs/weapon/WeaponDisplayRow.java, src/com/trollworks/gcs/weapon/WeaponStats.java
This adds tooltips for Weapon Damage and Spells.   It is a slightly bigger PR than before, but it follows the same pattern as Skill.
1.  I had to increase the tooltip time so that the user has time to actually read the bonuses.   I wasn't certain where you would want that kind of change, so I put it in GCS.java.
2.  The other GURPSCharacter "get*Bonus*" methods had to be updated to include the tooltip.
3.  In the previous PR, I did not completely update the PrerequisitesThread class.   I missed a few places where the parent needed to be set.
4.  Similar to the Skill PR, Spell's now use an instance of SkillLevel to maintain their level and relative level.   Also, the Spell calculation methods needed to be updated with tooltips.
5.  SpellColumn now shows tooltips for the Level and Relative …
=> Added tooltips for Spells & Weapon Damage

src/com/trollworks/gcs/skill/SkillEditor.java, src/com/trollworks/gcs/spell/SpellEditor.java
The final PR for tooltips (well, for now, at least).   Added the tooltip to the read only level field in the Skill/Spell editors (so you can see why the Skill/Spell is what it is while you are trying to decide how many points to put into it).
=> Added tooltips to Skill/Spell editors

src/com/trollworks/gcs/character/GURPSCharacter.java, src/com/trollworks/gcs/criteria/StringCompareType.java, src/com/trollworks/gcs/criteria/StringCriteria.java, src/com/trollworks/gcs/feature/SkillBonus.java, src/com/trollworks/gcs/feature/SkillBonusEditor.java, src/com/trollworks/gcs/skill/Skill.java, src/com/trollworks/gcs/skill/SkillEditor.java, src/com/trollworks/gcs/skill/Technique.java, src/com/trollworks/gcs/skill/TechniqueEditor.java, src/com/trollworks/gcs/widgets/outline/ListRow.java
Added bonuses by category for Skills.   This one is kind of messy because of the necessity of passing the categories around.
1.  The "get*Bonus*" methods in GURPSCharacter now accept a category string (actually, a single string of all categories separated by commas), and when they are comparing the bonus to see if it matches, they now also check the category criteria.
2.  To shorten some of the criteria checking code, they can now respond directly if they are "an exact match" kind of criteria (Is), or an "anything goes" kind (isAnything).
3.  SkillBonus gained a category criteria and all of the internal methods were updated to include it (object creation, copy, XML read/write, etc.).   Also, a SkillBonus can now determine if it matchesCategories().
4.  The SkillBonusEditor gained a …
=> Added bonus/feature by category for Skills

src/com/trollworks/gcs/character/GURPSCharacter.java, src/com/trollworks/gcs/feature/SpellBonus.java, src/com/trollworks/gcs/feature/SpellBonusEditor.java, src/com/trollworks/gcs/spell/Spell.java, src/com/trollworks/gcs/spell/SpellEditor.java
This builds off of (and partially copies) the Skill categories code.   The biggest issue here was the multiple ways you could add a spell bonus (by college, by name, by Power, etc.).
I built a large testcase that created bonuses for all of the combinations of college/power/name and category, to verify that the code works (and doesn't interfere with previous bonuses).  So on this, you will have to trust me ;-)  
The final PR will contain the code to support weapon bonuses by category.
=> Added Category filtering to Spell Bonuses

src/com/trollworks/gcs/character/GURPSCharacter.java, src/com/trollworks/gcs/feature/WeaponBonus.java, src/com/trollworks/gcs/feature/WeaponBonusEditor.java, src/com/trollworks/gcs/weapon/WeaponStats.java
The last of the "categories" change sets.   This adds category filtering to weapons bonuses.    The only real difference is that the "owner" of a WeaponStat could be something other than Equipment, and if so, we won't know what categories it belongs to (so we send null).   And we had to protect the WeaponBonus matchesCategories() method in case the categories were null.
=> Categories for Weapons Bonuses

src/com/trollworks/gcs/character/TextTemplate.java
Simple addition to the text output routine to also allow [ ] and { } around descriptive notes and modifiers.  I have already updated the web branch (and PR) with the additional information.
=> Added brackets and curly braces to text output

src/com/trollworks/gcs/character/CharacterSheet.java, src/com/trollworks/gcs/character/GURPSCharacter.java, src/com/trollworks/gcs/character/PrerequisitesThread.java, src/com/trollworks/gcs/preferences/SheetPreferences.java
I believe this solves https://github.com/richardwilkes/gcs/issues/97.  Since they were requesting "no modification to Basic Lifting and trait costs", it seemed simple enough.
It adds a preference option "Use optional Thrust damage (Thrust = Swing - 2)", and then just redirects the getThrust() method to the getSwing() method, minus 2.
I tested the notifications (although, I must admit, I was blindly copying code), but it seems to work correctly.   If you change the option, you will see the Thr damage change, and you will see all of the weapon damages change (based on thrust).
=> Added Thr=SW-2 damage option

com.trollworks.gcs/src/com/trollworks/gcs/ui/widget/dock/DockContainer.java
Adds `ctrl+tab` and `ctrl+shift+tab` as shortcuts to cycle through the tabs of `DockContainer` when it, or any descendent, has focus.
The change motivated by the fact that a lot* of software uses those shortcuts to switch tabs. Among those I have open at the moment, my file explorer, firefox, vscode and intellij have this behavior.
The ctrl modifier is actually chosen using the same code used by menu commands. I hope this makes it cross-platform (i.e. uses ctrl on win and linux, cmd on Mac) but I cannot test it.
As far as I could tell the shortcuts do not interfere with normal focus traversal, except for the loss of ability to change focus even with ctrl held down (but who does that anyway?).
\*A subjective lot
=> Add ctrl+tab shortcut to switch current tab of DockContainer

com.trollworks.gcs/src/com/trollworks/gcs/character/CharacterSheet.java, com.trollworks.gcs/src/com/trollworks/gcs/character/Settings.java, com.trollworks.gcs/src/com/trollworks/gcs/character/SettingsEditor.java, com.trollworks.gcs/src/com/trollworks/gcs/preferences/DisplayPreferences.java, com.trollworks.gcs/src/com/trollworks/gcs/preferences/Preferences.java
Currently, when trying to fill the entire width of the page, the FP/HP panel is stretched, which results in very wide FP/HP fields. This change makes it so the encumbrance panel fills the empty space instead, which is less noticeable and that's how it was done in the old layout.
=> Stretch encumbrance/lift panel instead of FP/HP panel.

com.trollworks.gcs/src/com/trollworks/gcs/pageref/PDFViewer.java
Note: technically both readers can be built on windows, but I'm unaware if anyone actually uses them there.
=> Support Okular and qpdfview on Linux

bundler/bundler/Bundler.java
Hey Rich,
I'm working on bundling GCS as an AppImage/Flatpak as we discussed in Discord and have discovered a couple of invalid settings in the Linux bundle.
The .desktop file categories are case sensitive, so `desktop-file-validate` is exiting with a code 1 when it looks at "Roleplaying" instead of "RolePlaying". This is causing `pkg2appimage` to exit as well. It's trivial, but still a problem. I'm basing the AppImage on your latest debian release so it would be helpful if these categories were updated. If you're curious about categories see the [Freedesktop Menu Spec](https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry)
I know this debian is no ta part of any official repo, but the section is also invalid. The section is defined by …
=> Add valid categories for freedesktop and section for dpkg/debian

com.trollworks.gcs/src/com/trollworks/gcs/settings/DamageProgression.java
Adds a new damage progression which computes sw damage as Basic Set's thr+2.
As far as I can tell, this originated with Kevin Smyth, with the goal of (a) making thr weapons competitive (and in that way working quite like `THRUST_EQUALS_SWING_MINUS_2`) and (b) making armour matter more. It's been talked about quite a bit on Douglas Cole's discord, but I don't know of any written-up post for it, just this [session recap](https://gamingballistic.com/2020/12/04/df-eastmarch-boss-fight-and-house-rules/).
Since I want to use it in my game, I thought I'd include it here.
P.S.: I really like the refactoring you did for `DamageProgression.java ` at some point after integrating the `THRUST_EQUALS_SWING_MINUS_2` pull request; that makes adding this one here a breeze!
=> Add new DamageProgression of sw = thr + 2

server/server.go, server/sheets.go
deflate is normally well-supported across browsers but MapTool only supports gzip out of the box.
It indicates this correctly by only sending gzip in Accept-Encoding though so we can test for this and only compress if it includes deflate.
I have submitted https://github.com/RPTools/maptool/pull/5016 to add support to MapTool also so it can support compressed encoding when the next release comes out.
=> Only send deflate encoded responses when supported
